export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
  users,
  notification,
}: {
  children: React.ReactNode;
  users: React.ReactNode;
  notification: React.ReactNode;
}) {
  return (
    <div>
      <div>{children}</div>
      <div>
        <div>{users}</div>
        <div>{notification}</div>
      </div>
    </div>
  );
}
